The "emissions profile" measures the absolute GHG emissions of a product in
comparison to a chosen benchmark of products. The assessment is first performed
on a product-level and can then be aggregated to the company-level. The profile
is expressed as the share of a company's products that are in a "high",
"medium", or "low" emission profile category, based on the comparison to the
benchmark. A higher emission profile indicates a larger impact on climate change
compared to the benchmark and can therefore also be interpreted as one climate
risk component to assess products, companies, or loan portfolios.

```{r include=FALSE}
bm <- tiltIndicator:::flat_benchmarks(tiltIndicator:::example_products())
bm <- paste0("`", bm, "`")
```

The "emission profile" is calculated in these steps: 

* The relative GHG emissions per product are collected from a
Life-Cycle-Analysis (LCA) database by matching the products from our company
dataset to the products from the LCA dataset.
* All products are ranked according to their GHG emissions. 
* The products are grouped by the following benchmarks:
  1. `r bm[[1]]`: All products.
  1. `r bm[[2]]`: All products within the same ISIC 4 digit code (example: 0112 Growing of rice).
  1. `r bm[[3]]`: All products within the same tilt sector (example: agriculture).
  1. `r bm[[4]]`: All products with the same unit (example: kg).
  1. `r bm[[5]]`: All products with the same unit within the same ISIC 4 digit section (example: kg + 0112 Growing of rice).
  1. `r bm[[6]]`: All products with the same unit within the same tilt sector (example: kg + agriculture).
* For each benchmark, products are assigned to the emission profile category
"low", "medium" or "high", depending on the GHG emissions arising from their
production process in comparison to all other products within the same
benchmark. For the assignment of the three categories, thresholds are used.
Please find more information about the thresholds in the
[Thresholds](https://2degreesinvesting.github.io/tiltIndicator/articles/tiltIndicator.html#thresholds)
section.

For the company-level results, we aggregate all products from the same category
and benchmark and set them in relation to all products that the company
produces. The company-level results are expressed as the company's share of
products per category "low", "medium", and "high" in comparison to each
benchmark.

The output of this indicator contains the following:

* A column indicating the benchmark to which a product is compared.
* A column indicating whether the product has "low", "medium" or "high" relative
GHG emissions.
* A column indicating the share of the products per category and benchmark".
