---
title: "Extending results at product level with columns from input datasets"
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This article shows how to extend results at product level with columns from
input datasets.

```{r setup}
library(tiltIndicator)
library(tiltToyData)
library(tibble, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)
```

`r tiltIndicator:::document_optional_rowid()`

This example shows `emissions_profile()` but the same goes for other functions.

```{r}
companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products()) |>
  rowid_to_column("products_rowid")

result_at_product_level <- emissions_profile(companies, products) |>
  unnest_product()
result_at_product_level
```

The `*rowid` column allows you to extend the output at product level with
columns from the input.

```{r}
extension <- products |> select(matches(c("rowid", "sector", "isic")))
extension

extended <- result_at_product_level |> left_join(extension)
extended
```
