#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr count
#' @importFrom dplyr distinct
#' @importFrom dplyr distinct_all
#' @importFrom dplyr ends_with
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr near
#' @importFrom dplyr pull
#' @importFrom dplyr reframe
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarise
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom dplyr where
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 scale_fill_gradient2
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom glue glue
#' @importFrom lifecycle deprecate_warn
#' @importFrom lifecycle deprecated
#' @importFrom memoise memoise
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_df
#' @importFrom purrr map_dfr
#' @importFrom purrr map_lgl
#' @importFrom purrr walk
#' @importFrom readr col_character
#' @importFrom readr cols
#' @importFrom readr read_csv
#' @importFrom rlang .env
#' @importFrom rlang abort
#' @importFrom rlang set_names
#' @importFrom rlang warn
#' @importFrom stringr str_pad
#' @importFrom tibble as_tibble
#' @importFrom tibble rowid_to_column
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr expand
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr separate
#' @importFrom tidyr separate_wider_delim
#' @importFrom tidyr unite
#' @importFrom tidyr unnest
#' @importFrom tidyselect all_of
#' @importFrom tidyselect contains
#' @importFrom tiltToyData toy_emissions_profile_any_companies
#' @importFrom tiltToyData toy_emissions_profile_products
#' @importFrom tiltToyData toy_emissions_profile_upstream_products
#' @importFrom tiltToyData toy_sector_profile_any_scenarios
#' @importFrom tiltToyData toy_sector_profile_companies
#' @importFrom tiltToyData toy_sector_profile_upstream_companies
#' @importFrom tiltToyData toy_sector_profile_upstream_products
#' @importFrom utils hasName
#' @importFrom vctrs vec_assert
#' @importFrom withr local_envvar
#' @importFrom withr local_options
## usethis namespace: end
NULL
