# https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  call-workflow-passing-data:
    uses: 2DegreesInvesting/tiltDevTools/.github/workflows/reusable-R-CMD-check.yaml@main
    secrets: inherit
